### ISSUE TITLE
[Bug] Actions failure on step 3 (fixing broken sidebar)

### ISSUE THREAD

**Issue by papaissad** [skills/connect-the-dots#23] opened 2023-01-05 10:41 UTC
**Describe the bug**
When processing the step 7 of [activity fix broken sidebar](https://github.com/skills/connect-the-dots#keyboard-activity-fix-a-broken-sidebar), the actions / checks failed. You can see from my personal demo repo https://github.com/papaissad/introduction-to-github/actions/runs/3845139285/jobs/6548938363 

I was expecting the checks to be green before proceeding to the next steps of the skills / tutorial.
I don't see what i might have done wrong, or maybe it's just an issue.
Would you have a look please ?

![image](https://user-images.githubusercontent.com/112574651/210760547-17e9ce2e-158b-4251-86e6-9c9650d51c47.png)

**Comment by zainnaved123** [comment] 2023-02-01 22:37
Duplicate of #2

**Comment by VaishaliKotadiya** [comment] 2023-02-08 11:05
Duplicate of #2"

**Comment by sinsukehlab** [comment] 2023-02-10 05:39
This error occurred because the BASE_BRANCH_NAME env is not set in the previous version (v1.2.0) of skills/action-update-step.
Now that v1.2.1 is released, the error is fixed.

**Comment by heiskr** [comment] 2023-02-16 05:31
Thank you for opening this issue. I believe this issue has been resolved, but please let us know if this issue persists.

**Closed by heiskr** 2023-02-16 05:31 UTC
Labels: bug
